/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: UserAuth.proto */

#ifndef PROTOBUF_C_UserAuth_2eproto__INCLUDED
#define PROTOBUF_C_UserAuth_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Com__Caredear__AuthRequest Com__Caredear__AuthRequest;
typedef struct _Com__Caredear__AuthResponse Com__Caredear__AuthResponse;


/* --- enums --- */


/* --- messages --- */

struct  _Com__Caredear__AuthRequest
{
  ProtobufCMessage base;
  char *auth_token;
  char *auth_session;
  /*
   * which apk trigger this(bbs?netdisk?qinliang? etc...)
   */
  int32_t auth_sysid;
};
#define COM__CAREDEAR__AUTH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__caredear__auth_request__descriptor) \
    , NULL, NULL, 0 }


struct  _Com__Caredear__AuthResponse
{
  ProtobufCMessage base;
  /*
   * CDS_XXX code
   */
  int32_t result_code;
  /*
   * further error msg if it has
   */
  char *extra_msg;
  /*
   * the user's CID
   */
  protobuf_c_boolean has_caredear_id;
  uint64_t caredear_id;
};
#define COM__CAREDEAR__AUTH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&com__caredear__auth_response__descriptor) \
    , 0, NULL, 0,0 }


/* Com__Caredear__AuthRequest methods */
void   com__caredear__auth_request__init
                     (Com__Caredear__AuthRequest         *message);
size_t com__caredear__auth_request__get_packed_size
                     (const Com__Caredear__AuthRequest   *message);
size_t com__caredear__auth_request__pack
                     (const Com__Caredear__AuthRequest   *message,
                      uint8_t             *out);
size_t com__caredear__auth_request__pack_to_buffer
                     (const Com__Caredear__AuthRequest   *message,
                      ProtobufCBuffer     *buffer);
Com__Caredear__AuthRequest *
       com__caredear__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__caredear__auth_request__free_unpacked
                     (Com__Caredear__AuthRequest *message,
                      ProtobufCAllocator *allocator);
/* Com__Caredear__AuthResponse methods */
void   com__caredear__auth_response__init
                     (Com__Caredear__AuthResponse         *message);
size_t com__caredear__auth_response__get_packed_size
                     (const Com__Caredear__AuthResponse   *message);
size_t com__caredear__auth_response__pack
                     (const Com__Caredear__AuthResponse   *message,
                      uint8_t             *out);
size_t com__caredear__auth_response__pack_to_buffer
                     (const Com__Caredear__AuthResponse   *message,
                      ProtobufCBuffer     *buffer);
Com__Caredear__AuthResponse *
       com__caredear__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   com__caredear__auth_response__free_unpacked
                     (Com__Caredear__AuthResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Com__Caredear__AuthRequest_Closure)
                 (const Com__Caredear__AuthRequest *message,
                  void *closure_data);
typedef void (*Com__Caredear__AuthResponse_Closure)
                 (const Com__Caredear__AuthResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor com__caredear__auth_request__descriptor;
extern const ProtobufCMessageDescriptor com__caredear__auth_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_UserAuth_2eproto__INCLUDED */
