/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caredear_detecter_MainActivity */

#ifndef _Included_com_caredear_detecter_MainActivity
#define _Included_com_caredear_detecter_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caredear_detecter_MainActivity
 * Method:    startServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_caredear_detecter_MainActivity_startServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_caredear_detecter_MainActivity
 * Method:    startClient
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_caredear_detecter_MainActivity_startClient
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
