// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UpdateProfile.proto

#ifndef PROTOBUF_UpdateProfile_2eproto__INCLUDED
#define PROTOBUF_UpdateProfile_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace caredear {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_UpdateProfile_2eproto();
void protobuf_AssignDesc_UpdateProfile_2eproto();
void protobuf_ShutdownFile_UpdateProfile_2eproto();

class UpdateRequest;
class UpdateResponse;

enum Updatetype {
  MOBILE_PHONE = 0,
  EMAIL = 1,
  USER_NAME = 2,
  PASSWORD = 3,
  OTHERS = 4
};
bool Updatetype_IsValid(int value);
const Updatetype Updatetype_MIN = MOBILE_PHONE;
const Updatetype Updatetype_MAX = OTHERS;
const int Updatetype_ARRAYSIZE = Updatetype_MAX + 1;

const ::google::protobuf::EnumDescriptor* Updatetype_descriptor();
inline const ::std::string& Updatetype_Name(Updatetype value) {
  return ::google::protobuf::internal::NameOfEnum(
    Updatetype_descriptor(), value);
}
inline bool Updatetype_Parse(
    const ::std::string& name, Updatetype* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Updatetype>(
    Updatetype_descriptor(), name, value);
}
// ===================================================================

class UpdateRequest : public ::google::protobuf::Message {
 public:
  UpdateRequest();
  virtual ~UpdateRequest();

  UpdateRequest(const UpdateRequest& from);

  inline UpdateRequest& operator=(const UpdateRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateRequest& default_instance();

  void Swap(UpdateRequest* other);

  // implements Message ----------------------------------------------

  UpdateRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateRequest& from);
  void MergeFrom(const UpdateRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .com.caredear.Updatetype reg_type = 1;
  inline bool has_reg_type() const;
  inline void clear_reg_type();
  static const int kRegTypeFieldNumber = 1;
  inline ::com::caredear::Updatetype reg_type() const;
  inline void set_reg_type(::com::caredear::Updatetype value);

  // required string update_data = 2;
  inline bool has_update_data() const;
  inline void clear_update_data();
  static const int kUpdateDataFieldNumber = 2;
  inline const ::std::string& update_data() const;
  inline void set_update_data(const ::std::string& value);
  inline void set_update_data(const char* value);
  inline void set_update_data(const char* value, size_t size);
  inline ::std::string* mutable_update_data();
  inline ::std::string* release_update_data();
  inline void set_allocated_update_data(::std::string* update_data);

  // required string uid = 3;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 3;
  inline const ::std::string& uid() const;
  inline void set_uid(const ::std::string& value);
  inline void set_uid(const char* value);
  inline void set_uid(const char* value, size_t size);
  inline ::std::string* mutable_uid();
  inline ::std::string* release_uid();
  inline void set_allocated_uid(::std::string* uid);

  // optional string vcode = 4;
  inline bool has_vcode() const;
  inline void clear_vcode();
  static const int kVcodeFieldNumber = 4;
  inline const ::std::string& vcode() const;
  inline void set_vcode(const ::std::string& value);
  inline void set_vcode(const char* value);
  inline void set_vcode(const char* value, size_t size);
  inline ::std::string* mutable_vcode();
  inline ::std::string* release_vcode();
  inline void set_allocated_vcode(::std::string* vcode);

  // @@protoc_insertion_point(class_scope:com.caredear.UpdateRequest)
 private:
  inline void set_has_reg_type();
  inline void clear_has_reg_type();
  inline void set_has_update_data();
  inline void clear_has_update_data();
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_vcode();
  inline void clear_has_vcode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* update_data_;
  ::std::string* uid_;
  ::std::string* vcode_;
  int reg_type_;
  friend void  protobuf_AddDesc_UpdateProfile_2eproto();
  friend void protobuf_AssignDesc_UpdateProfile_2eproto();
  friend void protobuf_ShutdownFile_UpdateProfile_2eproto();

  void InitAsDefaultInstance();
  static UpdateRequest* default_instance_;
};
// -------------------------------------------------------------------

class UpdateResponse : public ::google::protobuf::Message {
 public:
  UpdateResponse();
  virtual ~UpdateResponse();

  UpdateResponse(const UpdateResponse& from);

  inline UpdateResponse& operator=(const UpdateResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UpdateResponse& default_instance();

  void Swap(UpdateResponse* other);

  // implements Message ----------------------------------------------

  UpdateResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UpdateResponse& from);
  void MergeFrom(const UpdateResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result_code = 1;
  inline bool has_result_code() const;
  inline void clear_result_code();
  static const int kResultCodeFieldNumber = 1;
  inline ::google::protobuf::int32 result_code() const;
  inline void set_result_code(::google::protobuf::int32 value);

  // optional string extra_msg = 2;
  inline bool has_extra_msg() const;
  inline void clear_extra_msg();
  static const int kExtraMsgFieldNumber = 2;
  inline const ::std::string& extra_msg() const;
  inline void set_extra_msg(const ::std::string& value);
  inline void set_extra_msg(const char* value);
  inline void set_extra_msg(const char* value, size_t size);
  inline ::std::string* mutable_extra_msg();
  inline ::std::string* release_extra_msg();
  inline void set_allocated_extra_msg(::std::string* extra_msg);

  // @@protoc_insertion_point(class_scope:com.caredear.UpdateResponse)
 private:
  inline void set_has_result_code();
  inline void clear_has_result_code();
  inline void set_has_extra_msg();
  inline void clear_has_extra_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* extra_msg_;
  ::google::protobuf::int32 result_code_;
  friend void  protobuf_AddDesc_UpdateProfile_2eproto();
  friend void protobuf_AssignDesc_UpdateProfile_2eproto();
  friend void protobuf_ShutdownFile_UpdateProfile_2eproto();

  void InitAsDefaultInstance();
  static UpdateResponse* default_instance_;
};
// ===================================================================


// ===================================================================

// UpdateRequest

// required .com.caredear.Updatetype reg_type = 1;
inline bool UpdateRequest::has_reg_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateRequest::set_has_reg_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateRequest::clear_has_reg_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateRequest::clear_reg_type() {
  reg_type_ = 0;
  clear_has_reg_type();
}
inline ::com::caredear::Updatetype UpdateRequest::reg_type() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateRequest.reg_type)
  return static_cast< ::com::caredear::Updatetype >(reg_type_);
}
inline void UpdateRequest::set_reg_type(::com::caredear::Updatetype value) {
  assert(::com::caredear::Updatetype_IsValid(value));
  set_has_reg_type();
  reg_type_ = value;
  // @@protoc_insertion_point(field_set:com.caredear.UpdateRequest.reg_type)
}

// required string update_data = 2;
inline bool UpdateRequest::has_update_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateRequest::set_has_update_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateRequest::clear_has_update_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateRequest::clear_update_data() {
  if (update_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    update_data_->clear();
  }
  clear_has_update_data();
}
inline const ::std::string& UpdateRequest::update_data() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateRequest.update_data)
  return *update_data_;
}
inline void UpdateRequest::set_update_data(const ::std::string& value) {
  set_has_update_data();
  if (update_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    update_data_ = new ::std::string;
  }
  update_data_->assign(value);
  // @@protoc_insertion_point(field_set:com.caredear.UpdateRequest.update_data)
}
inline void UpdateRequest::set_update_data(const char* value) {
  set_has_update_data();
  if (update_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    update_data_ = new ::std::string;
  }
  update_data_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.caredear.UpdateRequest.update_data)
}
inline void UpdateRequest::set_update_data(const char* value, size_t size) {
  set_has_update_data();
  if (update_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    update_data_ = new ::std::string;
  }
  update_data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.caredear.UpdateRequest.update_data)
}
inline ::std::string* UpdateRequest::mutable_update_data() {
  set_has_update_data();
  if (update_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    update_data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.caredear.UpdateRequest.update_data)
  return update_data_;
}
inline ::std::string* UpdateRequest::release_update_data() {
  clear_has_update_data();
  if (update_data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = update_data_;
    update_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateRequest::set_allocated_update_data(::std::string* update_data) {
  if (update_data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete update_data_;
  }
  if (update_data) {
    set_has_update_data();
    update_data_ = update_data;
  } else {
    clear_has_update_data();
    update_data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.caredear.UpdateRequest.update_data)
}

// required string uid = 3;
inline bool UpdateRequest::has_uid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UpdateRequest::set_has_uid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UpdateRequest::clear_has_uid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UpdateRequest::clear_uid() {
  if (uid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_->clear();
  }
  clear_has_uid();
}
inline const ::std::string& UpdateRequest::uid() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateRequest.uid)
  return *uid_;
}
inline void UpdateRequest::set_uid(const ::std::string& value) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_ = new ::std::string;
  }
  uid_->assign(value);
  // @@protoc_insertion_point(field_set:com.caredear.UpdateRequest.uid)
}
inline void UpdateRequest::set_uid(const char* value) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_ = new ::std::string;
  }
  uid_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.caredear.UpdateRequest.uid)
}
inline void UpdateRequest::set_uid(const char* value, size_t size) {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_ = new ::std::string;
  }
  uid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.caredear.UpdateRequest.uid)
}
inline ::std::string* UpdateRequest::mutable_uid() {
  set_has_uid();
  if (uid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    uid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.caredear.UpdateRequest.uid)
  return uid_;
}
inline ::std::string* UpdateRequest::release_uid() {
  clear_has_uid();
  if (uid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = uid_;
    uid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateRequest::set_allocated_uid(::std::string* uid) {
  if (uid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete uid_;
  }
  if (uid) {
    set_has_uid();
    uid_ = uid;
  } else {
    clear_has_uid();
    uid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.caredear.UpdateRequest.uid)
}

// optional string vcode = 4;
inline bool UpdateRequest::has_vcode() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UpdateRequest::set_has_vcode() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UpdateRequest::clear_has_vcode() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UpdateRequest::clear_vcode() {
  if (vcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    vcode_->clear();
  }
  clear_has_vcode();
}
inline const ::std::string& UpdateRequest::vcode() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateRequest.vcode)
  return *vcode_;
}
inline void UpdateRequest::set_vcode(const ::std::string& value) {
  set_has_vcode();
  if (vcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    vcode_ = new ::std::string;
  }
  vcode_->assign(value);
  // @@protoc_insertion_point(field_set:com.caredear.UpdateRequest.vcode)
}
inline void UpdateRequest::set_vcode(const char* value) {
  set_has_vcode();
  if (vcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    vcode_ = new ::std::string;
  }
  vcode_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.caredear.UpdateRequest.vcode)
}
inline void UpdateRequest::set_vcode(const char* value, size_t size) {
  set_has_vcode();
  if (vcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    vcode_ = new ::std::string;
  }
  vcode_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.caredear.UpdateRequest.vcode)
}
inline ::std::string* UpdateRequest::mutable_vcode() {
  set_has_vcode();
  if (vcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    vcode_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.caredear.UpdateRequest.vcode)
  return vcode_;
}
inline ::std::string* UpdateRequest::release_vcode() {
  clear_has_vcode();
  if (vcode_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = vcode_;
    vcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateRequest::set_allocated_vcode(::std::string* vcode) {
  if (vcode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete vcode_;
  }
  if (vcode) {
    set_has_vcode();
    vcode_ = vcode;
  } else {
    clear_has_vcode();
    vcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.caredear.UpdateRequest.vcode)
}

// -------------------------------------------------------------------

// UpdateResponse

// required int32 result_code = 1;
inline bool UpdateResponse::has_result_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UpdateResponse::set_has_result_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UpdateResponse::clear_has_result_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UpdateResponse::clear_result_code() {
  result_code_ = 0;
  clear_has_result_code();
}
inline ::google::protobuf::int32 UpdateResponse::result_code() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateResponse.result_code)
  return result_code_;
}
inline void UpdateResponse::set_result_code(::google::protobuf::int32 value) {
  set_has_result_code();
  result_code_ = value;
  // @@protoc_insertion_point(field_set:com.caredear.UpdateResponse.result_code)
}

// optional string extra_msg = 2;
inline bool UpdateResponse::has_extra_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UpdateResponse::set_has_extra_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UpdateResponse::clear_has_extra_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UpdateResponse::clear_extra_msg() {
  if (extra_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extra_msg_->clear();
  }
  clear_has_extra_msg();
}
inline const ::std::string& UpdateResponse::extra_msg() const {
  // @@protoc_insertion_point(field_get:com.caredear.UpdateResponse.extra_msg)
  return *extra_msg_;
}
inline void UpdateResponse::set_extra_msg(const ::std::string& value) {
  set_has_extra_msg();
  if (extra_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extra_msg_ = new ::std::string;
  }
  extra_msg_->assign(value);
  // @@protoc_insertion_point(field_set:com.caredear.UpdateResponse.extra_msg)
}
inline void UpdateResponse::set_extra_msg(const char* value) {
  set_has_extra_msg();
  if (extra_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extra_msg_ = new ::std::string;
  }
  extra_msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:com.caredear.UpdateResponse.extra_msg)
}
inline void UpdateResponse::set_extra_msg(const char* value, size_t size) {
  set_has_extra_msg();
  if (extra_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extra_msg_ = new ::std::string;
  }
  extra_msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:com.caredear.UpdateResponse.extra_msg)
}
inline ::std::string* UpdateResponse::mutable_extra_msg() {
  set_has_extra_msg();
  if (extra_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    extra_msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:com.caredear.UpdateResponse.extra_msg)
  return extra_msg_;
}
inline ::std::string* UpdateResponse::release_extra_msg() {
  clear_has_extra_msg();
  if (extra_msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = extra_msg_;
    extra_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void UpdateResponse::set_allocated_extra_msg(::std::string* extra_msg) {
  if (extra_msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete extra_msg_;
  }
  if (extra_msg) {
    set_has_extra_msg();
    extra_msg_ = extra_msg;
  } else {
    clear_has_extra_msg();
    extra_msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:com.caredear.UpdateResponse.extra_msg)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace caredear
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::com::caredear::Updatetype> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::caredear::Updatetype>() {
  return ::com::caredear::Updatetype_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_UpdateProfile_2eproto__INCLUDED
