// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tokendata.proto

package com.caredear;

public final class Tokendata {
  private Tokendata() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TokenDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string uid = 1;
    /**
     * <code>required string uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <code>required string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    // required string appid = 2;
    /**
     * <code>required string appid = 2;</code>
     */
    boolean hasAppid();
    /**
     * <code>required string appid = 2;</code>
     */
    java.lang.String getAppid();
    /**
     * <code>required string appid = 2;</code>
     */
    com.google.protobuf.ByteString
        getAppidBytes();

    // required string loging = 3;
    /**
     * <code>required string loging = 3;</code>
     */
    boolean hasLoging();
    /**
     * <code>required string loging = 3;</code>
     */
    java.lang.String getLoging();
    /**
     * <code>required string loging = 3;</code>
     */
    com.google.protobuf.ByteString
        getLogingBytes();

    // required string aes_string = 4;
    /**
     * <code>required string aes_string = 4;</code>
     */
    boolean hasAesString();
    /**
     * <code>required string aes_string = 4;</code>
     */
    java.lang.String getAesString();
    /**
     * <code>required string aes_string = 4;</code>
     */
    com.google.protobuf.ByteString
        getAesStringBytes();
  }
  /**
   * Protobuf type {@code com.caredear.TokenData}
   */
  public static final class TokenData extends
      com.google.protobuf.GeneratedMessage
      implements TokenDataOrBuilder {
    // Use TokenData.newBuilder() to construct.
    private TokenData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TokenData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TokenData defaultInstance;
    public static TokenData getDefaultInstance() {
      return defaultInstance;
    }

    public TokenData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TokenData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              appid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              loging_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              aesString_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caredear.Tokendata.internal_static_com_caredear_TokenData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caredear.Tokendata.internal_static_com_caredear_TokenData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caredear.Tokendata.TokenData.class, com.caredear.Tokendata.TokenData.Builder.class);
    }

    public static com.google.protobuf.Parser<TokenData> PARSER =
        new com.google.protobuf.AbstractParser<TokenData>() {
      public TokenData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TokenData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private java.lang.Object uid_;
    /**
     * <code>required string uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string appid = 2;
    public static final int APPID_FIELD_NUMBER = 2;
    private java.lang.Object appid_;
    /**
     * <code>required string appid = 2;</code>
     */
    public boolean hasAppid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string appid = 2;</code>
     */
    public java.lang.String getAppid() {
      java.lang.Object ref = appid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          appid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string appid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAppidBytes() {
      java.lang.Object ref = appid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string loging = 3;
    public static final int LOGING_FIELD_NUMBER = 3;
    private java.lang.Object loging_;
    /**
     * <code>required string loging = 3;</code>
     */
    public boolean hasLoging() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string loging = 3;</code>
     */
    public java.lang.String getLoging() {
      java.lang.Object ref = loging_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loging_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string loging = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLogingBytes() {
      java.lang.Object ref = loging_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loging_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string aes_string = 4;
    public static final int AES_STRING_FIELD_NUMBER = 4;
    private java.lang.Object aesString_;
    /**
     * <code>required string aes_string = 4;</code>
     */
    public boolean hasAesString() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string aes_string = 4;</code>
     */
    public java.lang.String getAesString() {
      java.lang.Object ref = aesString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aesString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string aes_string = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAesStringBytes() {
      java.lang.Object ref = aesString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aesString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = "";
      appid_ = "";
      loging_ = "";
      aesString_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAppid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoging()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAesString()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAppidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLogingBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAesStringBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAppidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLogingBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAesStringBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caredear.Tokendata.TokenData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caredear.Tokendata.TokenData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caredear.Tokendata.TokenData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caredear.Tokendata.TokenData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caredear.TokenData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.caredear.Tokendata.TokenDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caredear.Tokendata.TokenData.class, com.caredear.Tokendata.TokenData.Builder.class);
      }

      // Construct using com.caredear.Tokendata.TokenData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        appid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        loging_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        aesString_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenData_descriptor;
      }

      public com.caredear.Tokendata.TokenData getDefaultInstanceForType() {
        return com.caredear.Tokendata.TokenData.getDefaultInstance();
      }

      public com.caredear.Tokendata.TokenData build() {
        com.caredear.Tokendata.TokenData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caredear.Tokendata.TokenData buildPartial() {
        com.caredear.Tokendata.TokenData result = new com.caredear.Tokendata.TokenData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.appid_ = appid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loging_ = loging_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.aesString_ = aesString_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caredear.Tokendata.TokenData) {
          return mergeFrom((com.caredear.Tokendata.TokenData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caredear.Tokendata.TokenData other) {
        if (other == com.caredear.Tokendata.TokenData.getDefaultInstance()) return this;
        if (other.hasUid()) {
          bitField0_ |= 0x00000001;
          uid_ = other.uid_;
          onChanged();
        }
        if (other.hasAppid()) {
          bitField0_ |= 0x00000002;
          appid_ = other.appid_;
          onChanged();
        }
        if (other.hasLoging()) {
          bitField0_ |= 0x00000004;
          loging_ = other.loging_;
          onChanged();
        }
        if (other.hasAesString()) {
          bitField0_ |= 0x00000008;
          aesString_ = other.aesString_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasAppid()) {
          
          return false;
        }
        if (!hasLoging()) {
          
          return false;
        }
        if (!hasAesString()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caredear.Tokendata.TokenData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caredear.Tokendata.TokenData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string uid = 1;
      private java.lang.Object uid_ = "";
      /**
       * <code>required string uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }

      // required string appid = 2;
      private java.lang.Object appid_ = "";
      /**
       * <code>required string appid = 2;</code>
       */
      public boolean hasAppid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string appid = 2;</code>
       */
      public java.lang.String getAppid() {
        java.lang.Object ref = appid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          appid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string appid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAppidBytes() {
        java.lang.Object ref = appid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string appid = 2;</code>
       */
      public Builder setAppid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string appid = 2;</code>
       */
      public Builder clearAppid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        appid_ = getDefaultInstance().getAppid();
        onChanged();
        return this;
      }
      /**
       * <code>required string appid = 2;</code>
       */
      public Builder setAppidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        appid_ = value;
        onChanged();
        return this;
      }

      // required string loging = 3;
      private java.lang.Object loging_ = "";
      /**
       * <code>required string loging = 3;</code>
       */
      public boolean hasLoging() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string loging = 3;</code>
       */
      public java.lang.String getLoging() {
        java.lang.Object ref = loging_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loging_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string loging = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLogingBytes() {
        java.lang.Object ref = loging_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loging_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string loging = 3;</code>
       */
      public Builder setLoging(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loging_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string loging = 3;</code>
       */
      public Builder clearLoging() {
        bitField0_ = (bitField0_ & ~0x00000004);
        loging_ = getDefaultInstance().getLoging();
        onChanged();
        return this;
      }
      /**
       * <code>required string loging = 3;</code>
       */
      public Builder setLogingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loging_ = value;
        onChanged();
        return this;
      }

      // required string aes_string = 4;
      private java.lang.Object aesString_ = "";
      /**
       * <code>required string aes_string = 4;</code>
       */
      public boolean hasAesString() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string aes_string = 4;</code>
       */
      public java.lang.String getAesString() {
        java.lang.Object ref = aesString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          aesString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string aes_string = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAesStringBytes() {
        java.lang.Object ref = aesString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aesString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string aes_string = 4;</code>
       */
      public Builder setAesString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        aesString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string aes_string = 4;</code>
       */
      public Builder clearAesString() {
        bitField0_ = (bitField0_ & ~0x00000008);
        aesString_ = getDefaultInstance().getAesString();
        onChanged();
        return this;
      }
      /**
       * <code>required string aes_string = 4;</code>
       */
      public Builder setAesStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        aesString_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caredear.TokenData)
    }

    static {
      defaultInstance = new TokenData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caredear.TokenData)
  }

  public interface TokenResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 result_code = 1;
    /**
     * <code>required int32 result_code = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required int32 result_code = 1;</code>
     */
    int getResultCode();

    // optional string error_code = 2;
    /**
     * <code>optional string error_code = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional string error_code = 2;</code>
     */
    java.lang.String getErrorCode();
    /**
     * <code>optional string error_code = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorCodeBytes();
  }
  /**
   * Protobuf type {@code com.caredear.TokenResult}
   */
  public static final class TokenResult extends
      com.google.protobuf.GeneratedMessage
      implements TokenResultOrBuilder {
    // Use TokenResult.newBuilder() to construct.
    private TokenResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TokenResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TokenResult defaultInstance;
    public static TokenResult getDefaultInstance() {
      return defaultInstance;
    }

    public TokenResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TokenResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caredear.Tokendata.internal_static_com_caredear_TokenResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caredear.Tokendata.internal_static_com_caredear_TokenResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caredear.Tokendata.TokenResult.class, com.caredear.Tokendata.TokenResult.Builder.class);
    }

    public static com.google.protobuf.Parser<TokenResult> PARSER =
        new com.google.protobuf.AbstractParser<TokenResult>() {
      public TokenResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TokenResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TokenResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 result_code = 1;
    public static final int RESULT_CODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>required int32 result_code = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 result_code = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    // optional string error_code = 2;
    public static final int ERROR_CODE_FIELD_NUMBER = 2;
    private java.lang.Object errorCode_;
    /**
     * <code>optional string error_code = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string error_code = 2;</code>
     */
    public java.lang.String getErrorCode() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorCodeBytes() {
      java.lang.Object ref = errorCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      resultCode_ = 0;
      errorCode_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorCodeBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getErrorCodeBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.caredear.Tokendata.TokenResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.caredear.Tokendata.TokenResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.caredear.Tokendata.TokenResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.caredear.Tokendata.TokenResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.caredear.TokenResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.caredear.Tokendata.TokenResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.caredear.Tokendata.TokenResult.class, com.caredear.Tokendata.TokenResult.Builder.class);
      }

      // Construct using com.caredear.Tokendata.TokenResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.caredear.Tokendata.internal_static_com_caredear_TokenResult_descriptor;
      }

      public com.caredear.Tokendata.TokenResult getDefaultInstanceForType() {
        return com.caredear.Tokendata.TokenResult.getDefaultInstance();
      }

      public com.caredear.Tokendata.TokenResult build() {
        com.caredear.Tokendata.TokenResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.caredear.Tokendata.TokenResult buildPartial() {
        com.caredear.Tokendata.TokenResult result = new com.caredear.Tokendata.TokenResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.caredear.Tokendata.TokenResult) {
          return mergeFrom((com.caredear.Tokendata.TokenResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.caredear.Tokendata.TokenResult other) {
        if (other == com.caredear.Tokendata.TokenResult.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasErrorCode()) {
          bitField0_ |= 0x00000002;
          errorCode_ = other.errorCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.caredear.Tokendata.TokenResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.caredear.Tokendata.TokenResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 result_code = 1;
      private int resultCode_ ;
      /**
       * <code>required int32 result_code = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 result_code = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required int32 result_code = 1;</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 result_code = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }

      // optional string error_code = 2;
      private java.lang.Object errorCode_ = "";
      /**
       * <code>optional string error_code = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string error_code = 2;</code>
       */
      public java.lang.String getErrorCode() {
        java.lang.Object ref = errorCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          errorCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorCodeBytes() {
        java.lang.Object ref = errorCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_code = 2;</code>
       */
      public Builder setErrorCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_code = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = getDefaultInstance().getErrorCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_code = 2;</code>
       */
      public Builder setErrorCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.caredear.TokenResult)
    }

    static {
      defaultInstance = new TokenResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.caredear.TokenResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caredear_TokenData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caredear_TokenData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_caredear_TokenResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_caredear_TokenResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017tokendata.proto\022\014com.caredear\"K\n\tToken" +
      "Data\022\013\n\003uid\030\001 \002(\t\022\r\n\005appid\030\002 \002(\t\022\016\n\006logi" +
      "ng\030\003 \002(\t\022\022\n\naes_string\030\004 \002(\t\"6\n\013TokenRes" +
      "ult\022\023\n\013result_code\030\001 \002(\005\022\022\n\nerror_code\030\002" +
      " \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_caredear_TokenData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_caredear_TokenData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_caredear_TokenData_descriptor,
              new java.lang.String[] { "Uid", "Appid", "Loging", "AesString", });
          internal_static_com_caredear_TokenResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_caredear_TokenResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_caredear_TokenResult_descriptor,
              new java.lang.String[] { "ResultCode", "ErrorCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
