# Travis-CI Build for rabbitmq-c
# see travis-ci.org for details

language: c

# Need to install libpopt-dev for tools build. Can use the container-based
# builds on travis once https://github.com/travis-ci/travis-ci/issues/3887 has
# been resolved.
sudo: required

# OSX isn't actually enabled at this point as we missed the boat. Hopefully
# they re-open sign-ups for OSS projects sometime soon.
os:
  - linux
  - osx

# Settings to try
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gDwqo3jHj+HHGzFKnxL/nwZhbVeh2pItw0TbeaHcLtWubUZaf85ViEQRaXPyfnbG7l0OEQq+PjyhKAfvViVq2NP0lGeeu4VM5uMZJhsCLN594BJr39Y4XzOapg0O8mEMhQ0DU2u1Zo4LMgEcRz67aosVQOj6QV30tOzp9fnxn9U="

matrix:
  include:
    - compiler: gcc
      env: CONFIG=autotools
    - compiler: gcc
      env: CONFIG=cmake
    - compiler: clang
      env: CONFIG=cmake
    - compiler: clang
      env: CONFIG=asan
    - compiler: clang
      env: CONFIG=tsan

# Make sure CMake is installed
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpopt-dev

# Run the Build script
script:
  - ./travis.sh $CONFIG

addons:
  coverity_scan:
    project:
      name: "alanxz/rabbitmq-c"
      description: "C AMQP client for RabbitMQ"
    notification_email: alan.antonuk@gmail.com
    build_command_prepend: cmake ..
    build_command: cmake --build .
    branch_pattern: coverity_scan
